In [64]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
for x in np.nditer(a,order='C'): # tutaj idzie wierszami
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [66]:
for x in np.nditer(a,order='F'):
    #print(x) # tutaj idzie kolumnami
    x = x*x
    print(x)
a = a + 2

0
16
64
1
25
81
4
36
100
9
49
121
