In [80]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


In [81]:
digits = load_digits()
df = pd.DataFrame(digits.data)
df['target'] = digits.target
LR = LogisticRegression()
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(['target'],axis = 'columns'),df.target,test_size =0.2)
LR.fit(X_train,Y_train)
LR.score(X_test, Y_test)


c:\Users\adria\miniconda3\envs\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

In [82]:
digits = load_digits()
df = pd.DataFrame(digits.data)
df['target'] = digits.target
SC = SVC()
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(['target'],axis = 'columns'),df.target,test_size =0.2)
SC.fit(X_train,Y_train)
SC.score(X_test, Y_test)

0.9777777777777777

In [83]:
from sklearn.ensemble import RandomForestClassifier
digits = load_digits()
df = pd.DataFrame(digits.data)
df['target'] = digits.target
model = RandomForestClassifier()
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(['target'],axis = 'columns'),df.target,test_size =0.2)
model.fit(X_train,Y_train)
model.score(X_test, Y_test)

0.975

In [84]:
from sklearn.model_selection import KFold
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [85]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,  test_index)
    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [86]:
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)

In [87]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
folds = StratifiedKFold(n_splits=3)



In [88]:
cross_val_score(LogisticRegression(),digits.data, digits.target).mean()



c:\Users\adria\miniconda3\envs\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\adria\miniconda3\envs\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

0.9137650882079852

In [102]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target).mean()

0.9360213556174559

In [100]:
cross_val_score(SVC(),digits.data, digits.target).mean()

0.9632838130609718

In [91]:
cross_val_score(SVC(kernel = 'linear'),digits.data, digits.target).mean()

0.9476973073351903

In [92]:
cross_val_score(SVC(kernel = 'poly'),digits.data, digits.target).mean()

0.9705106778087279

In [93]:
cross_val_score(SVC(kernel = 'sigmoid'),digits.data, digits.target).mean()

0.8803775920767564