In [7]:
import numpy as np
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:

b = np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
c = a + 2*b
print(c)

[ 0  3  6  9 12 15 18 21 24 27 30 33]


In [10]:
d = np.arange(9).reshape(3,3)
for row in d:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [11]:
e = np.arange(12).reshape(3,4)
for row in e:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [12]:
e = np.arange(12).reshape(3,4)
for row in e:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
