In [154]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn import linear_model 

In [155]:
df = pd.read_csv('homeprices.csv')
df.head(5)

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

Tworzymy Dummy

In [156]:
dummies = pd.get_dummies(df.town).astype(int)# dodanbie astype int zamienia true na false


In [157]:
merged = pd.concat([df,dummies],axis = 'columns')


In [158]:
final = merged.drop(['town','west windsor'], axis = 'columns')
final.head(4)

area   price  monroe township  robinsville
0  2600  550000                1            0
1  3000  565000                1            0
2  3200  610000                1            0
3  3600  680000                1            0

In [159]:

model = linear_model.LinearRegression()

In [160]:
X = final.drop('price',axis = 'columns')


In [161]:
Y = final.price


In [162]:
model.fit(X,Y)

LinearRegression()

In [163]:
model.predict([[2800,1,0]])#pierwsz parametr to powierzchnia drugi to czy jest to miasto monroe jesli tak to 1 itd, oba zera mowia o miescie west winsdor

c:\Users\adria\miniconda3\envs\myenv\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([565089.22812299])

In [164]:
model.predict([[2800,0,0]])

c:\Users\adria\miniconda3\envs\myenv\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([605103.20361213])

In [165]:
acuuracy = model.score(X,Y)
print('accuracy is:',round(acuuracy,3)*100,'%')

accuracy is: 95.7 %


In [166]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle =df 
dfle.town = le.fit_transform(dfle.town)#dopasujemy ze dany numer w town odpowiada konkretnemu miastu
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [167]:
X = dfle[['town','area']].values# dwuwymiarowa tablica


In [168]:
Y = dfle.price


In [169]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Assuming your data is in a variable named 'X' and the categorical feature is in the first column
# Replace '0' with the actual index of your categorical feature in your dataset
column_transformer = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])
    ],
    remainder='passthrough'
)

X_encoded = column_transformer.fit_transform(X)
X = X_encoded


In [170]:
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [171]:
model.fit(X,Y)

LinearRegression()

In [175]:
model.predict([[1,0,2800]]) #cena domu w robinson


array([590775.63964739])

In [176]:
model.predict([[0,1,3400]]) #cena domu wislson

array([681241.6684584])